#24-created-new-random-event-class
LaurenEBaker/Corprate_Hellscape pull request #31
Opened 2023-10-26 18:49 UTC by LaurenEBaker

this was just to create the new class that extends events, I'm just slowly pushing it little by little instead of all at once.

2023-10-27 03:11 UTC, JMarlin commented
I respect the hustle and your thought process is pretty right on. I would normally say don't make a whole PR, just let me know when you want me to take a look and I can just look at the commits on your feature branch. 

But since you already have the PR made, you can just keep pushing changes to that branch and it should update the PR as well. So I guess we can use it as a communication tool.

2023-10-28 21:44 UTC, LaurenEBaker commented
I figured this way you could see what I have accomplished so far, along with some issues I've ran into. Mainly on line 40 of the main method. I changed the class type for RandomSpawner from abstract to not have that, but main is throwing the error that the constructor is undefined. I'm also having trouble understanding what you mean by:
 "For each case in the current switch, create a corresponding stub immediately triggered event. (the triggerAction() of the event can just do the println that's currently in each switch case)"
Would it be possible to reword what you mean by "stub immediately triggered event"?

2023-10-29 14:18 UTC, JMarlin commented
Just adding a note that @LaurenEBaker and I met on Friday and worked through some of the above questions. Should have good direction now

2023-11-06 20:07 UTC, JMarlin requested changes

2023-11-06 20:07 UTC, JMarlin commented on src/main/java/com/corporate/hellscape/events/Nothing.java
> +        hellscape.registerEvent(new Nothing(false));
No need to register a follow-up event, that should just be handled by the `RandomEvent`

2023-11-06 20:07 UTC, JMarlin commented on src/main/java/com/corporate/hellscape/events/Spider.java
> +        _triggerEnabled = _triggerEnabled; }
Should probably be `_triggerEnabled = triggerEnabled`

2023-11-06 20:07 UTC, JMarlin commented on src/main/java/com/corporate/hellscape/events/Spider.java
> +        hellscape.registerEvent(new Spider(false));
No need to register a follow-up event

2023-11-14 01:41 UTC, JMarlin requested changes

2023-11-14 01:41 UTC, JMarlin commented on src/main/java/com/corporate/hellscape/events/RandomEvent.java
> +		hellscape.registerEvent(Event.Gift);
I'm not sure what this line is supposed to do

2023-11-14 01:41 UTC, JMarlin commented on src/main/java/com/corporate/hellscape/events/RandomEvent.java
> +		hellscape.registerEvent(Event.Spider);
I'm not sure what this line is supposed to do

2023-11-14 01:41 UTC, JMarlin commented on src/main/java/com/corporate/hellscape/events/RandomEvent.java
> +		hellscape.registerEvent(Event.Nothing);
I'm not sure what this line is supposed to do

2023-11-14 19:38 UTC, JMarlin approved these changes

2023-11-14 19:40 UTC, merged