updates issue 36 complete
LaurenEBaker/Corprate_Hellscape pull request #42
Opened 2023-11-03 21:13 UTC by MoAlsa7

2023-11-06 20:15 UTC, JMarlin requested changes

2023-11-06 20:15 UTC, JMarlin commented on src/main/java/com/corporate/hellscape/events/CheckHygieneEvent.java
> +    public CheckHygieneEvent(Hellscape hellscape,Character character) {
No need to get the character in the constructor

2023-11-06 20:15 UTC, JMarlin commented on src/main/java/com/corporate/hellscape/events/CheckStaminaEvent.java
> +    public CheckStaminaEvent( Hellscape hellscape,Character character) {
No need to get the character in the constructor

2023-11-06 20:15 UTC, JMarlin commented on src/main/java/com/corporate/hellscape/events/StatusEventSleepLow.java
> +        return (character.getStamin() < 50);
Typo? Compile and test before submitting changes! (or, if you did and this compiled okay, go fix the method name too)

2023-11-06 20:31 UTC, MoAlsa7 commented on src/main/java/com/corporate/hellscape/events/CheckHygieneEvent.java
> +    public CheckHygieneEvent(Hellscape hellscape,Character character) {
completed updated and pushed it to PR

2023-11-06 20:32 UTC, MoAlsa7 commented on src/main/java/com/corporate/hellscape/events/StatusEventSleepLow.java
> +        return (character.getStamin() < 50);
no I changed one of the character stats from sleep to stamina because it makes more sense for stamina to deplete and the character needing sleep is a action so I had to change it everywhere but It compiles

2023-11-07 02:21 UTC, JMarlin commented on src/main/java/com/corporate/hellscape/events/StatusEventSleepLow.java
> +        return (character.getStamin() < 50);
The typo I'm talking about is `getStamin()` vs `getStamina()`

2023-11-07 02:27 UTC, MoAlsa7 commented on src/main/java/com/corporate/hellscape/events/StatusEventSleepLow.java
> +        return (character.getStamin() < 50);
lol 😂

2023-11-07 02:40 UTC, JMarlin approved these changes

2023-11-07 02:41 UTC, merged